//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LangSchool.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ClientDetails
    {
        public string FIO { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<decimal> Age { get; set; }
        public Nullable<int> Tag { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
    }
}
